var KTRSCONSTANTS =
{
	CURRENT_RULE_TYPE:'current',
	YESTER_RULE_TYPE:'yester',
	DAY_CONST:'day',
	WEEK_CONST:'week',
	MONTH_CONST:'month',
	DATA_START_CONST:'dataStart',
	DATA_END_CONST:'dataEnd',
	DIV_CONST:'div',
	TIME_RANGE_VALUE_DIV_CLASSNAME:'timeRangeValue',
	IMG_CONST:'img',
	KTRS_CLOCK_IMAGEPATH:'images/clock-whiteface.svg',
	IMG_STYLE:'padding-left: 3px; padding-right: 5px;',
	SPAN_CONST:'span',
	TIME_RANGE_VALUE_SPANID:'timeRangeValueSpanID',
	TIME_RANGE_NONSELECTEDTEXT_CLASSNAME:'timeRangeNonSelectedText',
	TIME_RANGE_NONSELECTED_DISABLEDTEXT_CLASSNAME:'timeRangeNonSelectedDisabledText',
	TIME_RANGE_SELECTEDTEXT_CLASSNAME:'timeRangeSelectedText',
	TIME_RANGE_EVENT:'timeTangeEvent',
	UL_CONST:'ul',
	TIME_RANGE_QUICKLINK_DIV_CLASSNAME:'timeRangePresets btn-group',
	TIME_RANGE_QUICKLINK_UL_STYLE:'display: inline-block',
	TIME_RANGE_QUICKLINK_UL_CLASSNAME:'list-inline',
	LI_CONST:'li',
	A_CONST:'a',
	DATE_RANGE_PICKER_DIVID:'dateRangePickerDivID',
	DATE_RANGE_PICKER_DIV_CLASSNAME:'timeRangeCustom',
	CALENDAR_IMAGEPATH:'images/calendar.svg',
	GLYPHICON_CLASS:'glyphicon',
	DTRAPPLY_CLASSNAME:'btn-primary',
	DTRCANCEL_CLASSNAME:'btn-warning'
};